
services:
  fastapi-backend:
    container_name: "astro-backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - webnet-astro

  vite-react-tw-frontend:
    container_name: "astro-frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - webnet-astro

networks:
  webnet-astro:
    external: true